[package]
name = "qinpel-srv"
description = "QinpelSrv - Server for Qinpel applications and commands with file system and database source for authorized users."
repository = "https://github.com/emuvi/qinpel-srv/"
authors = ["Éverton M. Vieira"]
license = "LGPL-3.0-only"
version = "0.4.5"
edition = "2018"

[dependencies]
clap = "2"
actix-web = "3"
actix-files = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
rand = "0.8"
base64 = "0.13"