[package]
name = "qinpel-srv"
version = "0.2.2"
edition = "2018"

[dependencies]
clap = "2.33"
rocket = "0.4"
actix-web = "3"
actix-files = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"