[package]
name = "qinpel-srv"
version = "0.3.5"
edition = "2018"

[dependencies]
clap = "2"
actix-web = "3"
actix-files = "0.5"
actix-multipart = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
rand = "0.8"
futures = "0.3"
sanitize-filename = "0.3"
base64 = "0.13"
r2d2 = "0.8"
r2d2_sqlite = "0.18"
r2d2_postgres = "0.18"
rust_decimal = { version = "1.16", features = ["db-postgres"] }

[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled"]