[package]
name = "qinpel-srv"
version = "0.3.5"
edition = "2018"

[dependencies]
clap = "2"
actix-web = "3"
actix-files = "0.5"
actix-multipart = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
rand = "0.8"
futures = "0.3"
sanitize-filename = "0.2"
base64 = "0.13"